#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Modules (classes) interface."""

from typing import TYPE_CHECKING

from torch.nn.modules import *  # type: ignore

if TYPE_CHECKING:
    from .activation import LogSoftmaxMultidim, SoftmaxMultidim
    from .container import (
        EModuleDict,
        EModuleList,
        EModulePartial,
        ESequential,
        ModuleDict,
        ModuleList,
        ModulePartial,
        Sequential,
    )
    from .crop import CropDim, CropDims
    from .layer import PositionalEncoding
    from .mask import MaskedMean, MaskedSum
    from .module import EModule, Module
    from .multiclass import (
        IndexToName,
        IndexToOnehot,
        NameToIndex,
        NameToOnehot,
        OnehotToIndex,
        OnehotToName,
        ProbsToIndex,
        ProbsToName,
        ProbsToOnehot,
    )
    from .multilabel import (
        IndicesToMultihot,
        IndicesToMultinames,
        MultihotToIndices,
        MultihotToMultiIndices,
        MultihotToMultinames,
        MultiIndicesToMultihot,
        MultiIndicesToMultinames,
        MultinamesToIndices,
        MultinamesToMultihot,
        MultinamesToMultiIndices,
        ProbsToIndices,
        ProbsToMultihot,
        ProbsToMultiIndices,
        ProbsToMultinames,
    )
    from .numpy import NDArrayToTensor, TensorToNDArray, ToNDArray
    from .padding import PadAndStackRec, PadDim, PadDims
    from .powerset import MultilabelToPowerset, PowersetToMultilabel
    from .tensor import (
        FFT,
        IFFT,
        Abs,
        Angle,
        Exp,
        Exp2,
        Imag,
        Log,
        Log2,
        Log10,
        Max,
        Mean,
        Min,
        Normalize,
        Permute,
        Pow,
        Real,
        Repeat,
        RepeatInterleave,
        Reshape,
        Sort,
        TensorTo,
        ToList,
        Transpose,
        View,
    )
    from .transform import (
        AsTensor,
        Flatten,
        Identity,
        MoveToRec,
        PadAndCropDim,
        RepeatInterleaveNd,
        ResampleNearestFreqs,
        ResampleNearestRates,
        ResampleNearestSteps,
        Shuffled,
        Squeeze,
        ToItem,
        Topk,
        TopP,
        ToTensor,
        TransformDrop,
        Unsqueeze,
        ViewAsComplex,
        ViewAsReal,
    )
else:
    import lazy_loader as lazy

    __getattr__, __dir__, __all__ = lazy.attach(
        __name__,
        submodules=[
            "activation",
            "container",
            "crop",
            "layer",
            "mask",
            "module",
            "multiclass",
            "multilabel",
            "numpy",
            "padding",
            "powerset",
            "tensor",
            "transform",
        ],
        submod_attrs={
            "activation": ["LogSoftmaxMultidim", "SoftmaxMultidim"],
            "container": [
                "EModuleDict",
                "EModuleList",
                "EModulePartial",
                "ESequential",
                "ModuleDict",
                "ModuleList",
                "ModulePartial",
                "Sequential",
            ],
            "crop": ["CropDim", "CropDims"],
            "layer": ["PositionalEncoding"],
            "mask": ["MaskedMean", "MaskedSum"],
            "module": ["EModule", "Module"],
            "multiclass": [
                "IndexToName",
                "IndexToOnehot",
                "NameToIndex",
                "NameToOnehot",
                "OnehotToIndex",
                "OnehotToName",
                "ProbsToIndex",
                "ProbsToName",
                "ProbsToOnehot",
            ],
            "multilabel": [
                "IndicesToMultihot",
                "IndicesToMultinames",
                "MultihotToIndices",
                "MultihotToMultiIndices",
                "MultihotToMultinames",
                "MultiIndicesToMultihot",
                "MultiIndicesToMultinames",
                "MultinamesToIndices",
                "MultinamesToMultihot",
                "MultinamesToMultiIndices",
                "ProbsToIndices",
                "ProbsToMultihot",
                "ProbsToMultiIndices",
                "ProbsToMultinames",
            ],
            "numpy": ["NDArrayToTensor", "TensorToNDArray", "ToNDArray"],
            "padding": ["PadAndStackRec", "PadDim", "PadDims"],
            "powerset": ["MultilabelToPowerset", "PowersetToMultilabel"],
            "tensor": [
                "FFT",
                "IFFT",
                "Abs",
                "Angle",
                "Exp",
                "Exp2",
                "Imag",
                "Log",
                "Log2",
                "Log10",
                "Max",
                "Mean",
                "Min",
                "Normalize",
                "Permute",
                "Pow",
                "Real",
                "Repeat",
                "RepeatInterleave",
                "Reshape",
                "Sort",
                "TensorTo",
                "ToList",
                "Transpose",
                "View",
            ],
            "transform": [
                "AsTensor",
                "Flatten",
                "Identity",
                "MoveToRec",
                "PadAndCropDim",
                "RepeatInterleaveNd",
                "ResampleNearestFreqs",
                "ResampleNearestRates",
                "ResampleNearestSteps",
                "Shuffled",
                "Squeeze",
                "ToItem",
                "Topk",
                "TopP",
                "ToTensor",
                "TransformDrop",
                "Unsqueeze",
                "ViewAsComplex",
                "ViewAsReal",
            ],
        },
    )


del TYPE_CHECKING
