from pythonwrench.importlib import Placeholder

class BaseLoader(Placeholder): ...
class CBaseLoader(Placeholder): ...
class CFullLoader(Placeholder): ...
class CLoader(Placeholder): ...
class CSafeLoader(Placeholder): ...
class CUnsafeLoader(Placeholder): ...
class FullLoader(Placeholder): ...
class Loader(Placeholder): ...
class MappingNode(Placeholder): ...
class Node(Placeholder): ...
class SafeLoader(Placeholder): ...
class ScalarNode(Placeholder): ...
class SequenceNode(Placeholder): ...
class UnsafeLoader(Placeholder): ...
class ParserError(RuntimeError): ...
class ScannerError(RuntimeError): ...

def load(*args, **kwargs) -> None: ...
def dump(*args, **kwargs) -> None: ...
