from pathlib import Path

def get_tmp_dir(mkdir: bool = False, make_parents: bool = True) -> Path: ...
def get_cache_dir(mkdir: bool = False, make_parents: bool = True) -> Path: ...
def get_torch_cache_dir(*args, **kwargs) -> None: ...
