from typing import Any

from pythonwrench.importlib import Placeholder

class generic(Placeholder): ...
class number(generic): ...
class bool_(generic): ...
class str_(generic): ...
class dtype(Placeholder): ...

class ndarray(Placeholder):
    def __getitem__(self, *args) -> Any: ...

def array(x: Any, *args, **kwargs): ...
def asarray(x: Any, *args, **kwargs): ...
def iscomplexobj(x: Any): ...
def empty(*args, **kwargs) -> None: ...

class complex64(dtype): ...
class complex128(dtype): ...
class complex256(dtype): ...
class float16(dtype): ...
class float32(dtype): ...
class float64(dtype): ...
class float128(dtype): ...
class floating(dtype): ...
class int16(dtype): ...
class int32(dtype): ...
class int64(dtype): ...
class uint8(dtype): ...
