from typing import Any, Iterable, Literal, overload

from pythonwrench import BuiltinScalar as BuiltinScalar
from torch import Tensor
from typing_extensions import TypeGuard

from torchwrench.core.make import DeviceLike as DeviceLike
from torchwrench.core.make import DTypeLike as DTypeLike
from torchwrench.core.make import as_device as as_device
from torchwrench.core.make import as_dtype as as_dtype
from torchwrench.extras.numpy.definitions import NumpyNumberLike as NumpyNumberLike
from torchwrench.extras.numpy.definitions import NumpyScalarLike as NumpyScalarLike
from torchwrench.extras.numpy.definitions import np as np

def to_ndarray(
    x: Tensor | np.ndarray | Iterable | BuiltinScalar,
    *,
    dtype: str | np.dtype | None = None,
    force: bool = False,
) -> np.ndarray: ...
def tensor_to_ndarray(
    x: Tensor, *, dtype: str | np.dtype | None = None, force: bool = False
) -> np.ndarray: ...
def ndarray_to_tensor(
    x: np.ndarray | np.number, *, device: DeviceLike = None, dtype: DTypeLike = None
) -> Tensor: ...
def numpy_view_as_real(x: np.ndarray) -> np.ndarray: ...
def numpy_complex_dtype_to_float_dtype(dtype: np.dtype) -> np.dtype: ...
def numpy_view_as_complex(x: np.ndarray) -> np.ndarray: ...
def numpy_is_floating_point(x: np.ndarray | np.generic) -> bool: ...
def numpy_is_complex(x: np.ndarray | np.generic) -> bool: ...
def numpy_is_complex_dtype(dtype: np.dtype) -> bool: ...
def is_numpy_bool_array(x: Any) -> TypeGuard[np.bool_ | np.ndarray]: ...
def is_numpy_str_array(x: Any) -> TypeGuard[np.str_ | np.ndarray]: ...
def is_numpy_integral_array(x: Any) -> TypeGuard[np.ndarray | np.generic]: ...
def is_numpy_number_like(x: Any) -> TypeGuard[NumpyNumberLike]: ...
def is_numpy_scalar_like(x: Any) -> TypeGuard[NumpyScalarLike]: ...
def numpy_topk(
    x: np.ndarray, k: int, dim: int = -1, largest: bool = True, sorted: bool = True
) -> tuple[np.ndarray, np.ndarray]: ...
def numpy_item(x: np.ndarray | np.generic | BuiltinScalar) -> np.generic: ...
@overload
def numpy_all_eq(x: np.generic | np.ndarray, dim: Literal[None] = None) -> bool: ...
@overload
def numpy_all_eq(x: np.generic | np.ndarray, dim: int) -> np.ndarray: ...
def numpy_all_ne(x: np.generic | np.ndarray) -> bool: ...
def logical_and_lst(*args, **kwargs) -> None: ...
def logical_or_lst(*args, **kwargs) -> None: ...
def to_numpy(*args, **kwargs) -> None: ...
def tensor_to_numpy(*args, **kwargs) -> None: ...
def numpy_to_tensor(*args, **kwargs) -> None: ...
