from typing import Any

from pythonwrench.importlib import Placeholder

class DataFrame(Placeholder):
    def __getitem__(self, *args, **kwargs) -> Any: ...
    def __len__(self) -> int: ...
    def __setitem__(self, *args, **kwargs) -> Any: ...

class Series(Placeholder): ...
class RangeIndex(Placeholder): ...
class Index(Placeholder): ...

def read_csv(*args, **kwargs) -> DataFrame: ...
